### ISSUE TITLE
Add support for containerd runtime

### ISSUE THREAD

**Issue by safarmer** [pixie-labs/pixie#251]
**Is your feature request related to a problem? Please describe.**
When installing pixie on a cluster that uses the containerd runtime, most cluster metadata is missing.

**Comment by aimichelle** [comment]
Hey @safarmer , the fix for this has just rolled out in our latest release (0.7.7). If Pixie is still running on your cluster, it should already be auto-updated to the latest version. Otherwise, you can redeploy with `px deploy` and it should automatically deploy.

In case you're wondering, the changes for the fix are here: https://github.com/pixie-labs/pixie/commit/f6dca0f5b4fba1ae0d92cdfaa18839883458eebc
We look for "containerd" in the container ID, and use `cri-containerd` in the cgroup proc file path if that is the case.

Let us know if this worked for your environment!

**Comment by safarmer** [comment]
Thanks @aimichelle for the quick fix. I can confirm that cluster metadata is working correctly.

**Comment by aimichelle** [comment]
Awesome! Glad to hear that it's working now. Feel free to reach out again if you run into anything else/have any questions. 

Closing this issue now, since it's been resolved.
